# Generated by Django 2.2.7 on 2019-12-02 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('account_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
