# Generated by Django 2.2.7 on 2019-12-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserRegister',
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'Users Register'},
        ),
    ]
