# Generated by Django 2.2.7 on 2019-12-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191229_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Form'},
        ),
    ]
