# Generated by Django 2.2.7 on 2019-12-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('publication_status', models.CharField(max_length=50)),
                ('information_sources', models.TextField()),
                ('publication_image', models.ImageField(upload_to='')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('publication_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Publicaction')),
            ],
        ),
    ]
