# Generated by Django 2.2.7 on 2019-12-28 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191227_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginformation',
            name='descriptions',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='sources',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
