# Generated by Django 2.2.7 on 2019-12-28 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191228_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginformation',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
