# Generated by Django 2.2.7 on 2019-12-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191228_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created', '-updated'], 'verbose_name_plural': 'Publications'},
        ),
    ]
