# Generated by Django 2.2.7 on 2019-12-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191230_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created', 'updated'], 'verbose_name_plural': 'Publications'},
        ),
    ]
