# Generated by Django 2.2.7 on 2020-01-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191231_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginformation',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloginformation',
            name='descriptions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
