# Generated by Django 2.2.7 on 2019-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
